name: Publish Snapshot Release

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  snapshot-release:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        uses: backstage/actions/yarn-install@v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v20.x

      - name: Build Type Declarations
        run: yarn tsc

      - name: Build Packages
        run: yarn build:all

      - name: Create and Publish Snapshot
        run: |
          yarn changeset version --snapshot 'snapshot'
          yarn changeset publish --tag 'snapshot'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
